### ISSUE TITLE
The merge layer button looks too much like a download graphic.

### ISSUE THREAD

**Issue by JasonHoku** [piskelapp/piskel#1178]
I and another user both didn't recognize it as merge.

It could be updated to be more intuitive and less confusing by using a more clear merge icon instead.

![Image](https://github.com/user-attachments/assets/1d3bd886-0359-4430-b86e-060a6a21cdfb)

![Image](https://github.com/user-attachments/assets/15df565f-3082-4982-95a1-d6e438fa7266)

I tried for a bit to understand the code base deeply enough to submit a PR for this issue but I don't think I understand the frameworks well enough.

I found the classname for the icon here in `\piskel\src\css\font-icon.css` at line 62

```css
.piskel-icon-merge:before {
  content: "\e609";
}
```
And found mention of the unicode symbol as a glyph in this file: `\piskel\src\css\fonts\icomoon.svg`

But that seems to be where my mission comes to an end.

Would you all accept a simple svg and html replacement PR?

**Comment by mstphayassin** [comment]
@JasonHoku 
I have a question. If we changed
```css
.piskel-icon-merge:before {
  content: "\e609";
}
```
which refers to this image:
<img width="31" height="24" alt="Image" src="https://github.com/user-attachments/assets/3dad96e1-1c84-49bd-ad0b-2d9b36f4219b" />

to
```css
.piskel-icon-merge:before {
  content: "\e600";
}
```
which refers to this image:
<img width="31" height="24" alt="Image" src="https://github.com/user-attachments/assets/969d2d9e-a1f5-4108-95ab-a13eef4645a5" />

Would that address this issue? Does this look less like a download icon?

I only suggest this because it would only take the change of one digit in `\piskel\src\css\font-icon.css` rather than the recreation of 
- `fonts/icomoon.eot`
- `fonts/icomoon.woff`
- `fonts/icomoon.ttf`
- `fonts/icomoon.svg`
